defmodule Livemd2exsTest do
  use ExUnit.Case

  @fixtures_dir "test/fixtures"

  describe "extract/1" do
    test "includes shebang header" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "simple.livemd"))
      assert String.starts_with?(result, "#! /usr/bin/env elixir")
    end

    test "header contains source file path" do
      path = Path.join(@fixtures_dir, "simple.livemd")
      result = Livemd2exs.extract(path)
      assert result =~ "# livemd input: #{path}"
    end

    test "header contains generation timestamp" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "simple.livemd"))
      assert result =~ ~r/# Generated by `livemd2exs` on \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/
    end

    test "extracts a single code block" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "simple.livemd"))
      assert result =~ ~s[IO.puts("hello world")]
    end

    test "extracts multiple code blocks in order" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "multiple_blocks.livemd"))
      assert result =~ "x = 1\ny = 2"
      assert result =~ "sum = x + y"
      assert result =~ ~s[IO.puts("sum is \#{sum}")]

      # Verify ordering: first block appears before second, second before third
      pos1 = :binary.match(result, "x = 1") |> elem(0)
      pos2 = :binary.match(result, "sum = x + y") |> elem(0)
      pos3 = :binary.match(result, "IO.puts") |> elem(0)
      assert pos1 < pos2
      assert pos2 < pos3
    end

    test "code blocks are separated by blank lines" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "multiple_blocks.livemd"))
      assert result =~ "y = 2\n\nsum = x + y"
    end

    test "discards text content between code blocks" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "mixed_content.livemd"))
      refute result =~ "This is a text section"
      refute result =~ "explanatory text"
      refute result =~ "bullet one"
      refute result =~ "Another Section"
      refute result =~ "Final paragraph"
    end

    test "extracts only code blocks from mixed content" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "mixed_content.livemd"))
      assert result =~ "list = [1, 2, 3]"
      assert result =~ "Enum.map(list, &(&1 * 2))"
      assert result =~ ~s[IO.puts("done")]
    end

    test "returns header only when there are no code blocks" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "no_code.livemd"))
      assert String.starts_with?(result, "#! /usr/bin/env elixir")
      refute result =~ "Some explanatory text"
      # After the header, there should be no code content
      [_header | rest] = String.split(result, "\n\n", parts: 2)
      assert rest == [] or rest == [""]
    end

    test "handles empty file" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "empty.livemd"))
      assert String.starts_with?(result, "#! /usr/bin/env elixir")
    end

    test "extracts code blocks from llmdb livebook" do
      result = Livemd2exs.extract(Path.join(@fixtures_dir, "llmdb.livemd"))

      # Should contain all four code blocks
      assert result =~ "Mix.install"
      assert result =~ "LLMDB.providers()"
      assert result =~ ~s[&(&1.id == :anthropic)]
      assert result =~ "LLMDB.models(:anthropic)"
      assert result =~ ~s[LLMDB.model(:anthropic, "claude-haiku-4-5")]

      # Should not contain any prose
      refute result =~ "LLMDB Basics"
      refute result =~ "Intro / Configuration"
      refute result =~ "Model details are stored"
    end
  end
end
